export default [
    { nom: 'Bo├®court', potentielToit: 3.07 },
    { nom: 'Bourrignon', potentielToit: 1.21 },
    { nom: 'Ch├ótillon (JU)', potentielToit: 1.04 },
    { nom: 'Courchapoix', potentielToit: 1.22 },
    { nom: 'Courrendlin', potentielToit: 7.74 },
    { nom: 'Courroux', potentielToit: 7.71 },
    { nom: 'Court├®telle', potentielToit: 5.6 },
    { nom: 'Del├®mont', potentielToit: 24.69 },
    { nom: 'Develier', potentielToit: 4.11 },
    { nom: 'Ederswiler', potentielToit: 0.65 },
    { nom: 'Mervelier', potentielToit: 1.75 },
    { nom: 'Mettembert', potentielToit: 0.4 },
    { nom: 'Movelier', potentielToit: 1.55 },
    { nom: 'Pleigne', potentielToit: 1.52 },
    { nom: 'Rossemaison', potentielToit: 1.77 },
    { nom: 'Saulcy', potentielToit: 1.07 },
    { nom: 'Soyhi├¿res', potentielToit: 1.09 },
    { nom: 'Haute-Sorne', potentielToit: 18.39 },
    { nom: 'Val Terbi', potentielToit: 9.14 },
    { nom: 'Le B├®mont (JU)', potentielToit: 1.63 },
    { nom: 'Les Bois', potentielToit: 4.46 },
    { nom: 'Les Breuleux', potentielToit: 5.1 },
    { nom: 'La Chaux-des-Breuleux', potentielToit: 0.63 },
    { nom: 'Les Enfers', potentielToit: 0.71 },
    { nom: 'Les Genevez (JU)', potentielToit: 2.37 },
    { nom: 'Lajoux (JU)', potentielToit: 2.58 },
    { nom: 'Montfaucon', potentielToit: 3.07 },
    { nom: 'Muriaux', potentielToit: 2.5 },
    { nom: 'Le Noirmont', potentielToit: 5.8 },
    { nom: 'Saignel├®gier', potentielToit: 8.73 },
    { nom: 'Saint-Brais', potentielToit: 1.35 },
    { nom: 'Soubey', potentielToit: 0.64 },
    { nom: 'Alle', potentielToit: 5.53 },
    { nom: 'Beurnev├®sin', potentielToit: 0.56 },
    { nom: 'Boncourt', potentielToit: 3.99 },
    { nom: 'Bonfol', potentielToit: 2.4 },
    { nom: 'Bure', potentielToit: 2.41 },
    { nom: 'Coeuve', potentielToit: 2.35 },
    { nom: 'Cornol', potentielToit: 2.79 },
    { nom: 'Courchavon', potentielToit: 1.05 },
    { nom: 'Courgenay', potentielToit: 5.84 },
    { nom: 'Courtedoux', potentielToit: 2.27 },
    { nom: 'Damphreux', potentielToit: 0.67 },
    { nom: 'Fahy', potentielToit: 2.15 },
    { nom: 'Fontenais', potentielToit: 4.71 },
    { nom: 'Grandfontaine', potentielToit: 1.48 },
    { nom: 'Lugnez', potentielToit: 0.77 },
    { nom: 'Porrentruy', potentielToit: 16.18 },
    { nom: 'Vendlincourt', potentielToit: 2.35 },
    { nom: 'Basse-Allaine', potentielToit: 4.16 },
    { nom: 'Clos du Doubs', potentielToit: 5.47 },
    { nom: 'Haute-Ajoie', potentielToit: 5.01 },
    { nom: 'La Baroche', potentielToit: 4.79 }
  ]

  